blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions
    about: Ask questions and discuss with other community members
  - name: License issue
    url: https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2630
    about: Check your license status before you create a new issue
  - name: Issues about Rainbow Variables/Semantic Highlighting
    url: https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2760#issuecomment-2347960008
    about: Please upgrade your IDE to the latest before your raise a issue about Rainbow Variables/Semantic Highlighting
  - name: License issue about JetBrains Client/ IntelliJ Remote Development/ Code With Me/ JetBrains Gateway
    url: https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2888
    about: install the beta version for experimental support 
  - name: Rainbow Variables issue about JetBrains Client/ IntelliJ Remote Development/ Code With Me/ JetBrains Gateway
    url: https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2584
    about: JetBrains Client/IntelliJ Remote Development not supporte Rainbow Variables
  - name: com.intellij.modules.xml not found(JetBrains Client/ IntelliJ Remote Development/ Code With Me/ JetBrains Gateway)
    url: https://github.com/izhangzhihao/intellij-rainbow-brackets/discussions/2888
    about: install the beta version for experimental support 
